#!/usr/bin/env node
/**
 * Resets the test database to a clean state, then seeds the minimum data
 * needed for E2E tests:
 *  - A fresh test user (CREATOR role) + session token
 *  - A fresh no-role user (for onboarding flow tests)
 *  - BookletConstraint + open SubscriptionCycle
 *
 * Writes AUTH_BYPASS_TEST_USER_ID and TEST_SESSION_TOKEN to .env.test.local.
 * Also writes NO_ROLE_USER_ID and NO_ROLE_SESSION_TOKEN to the same file so
 * the onboarding tests can swap the authenticated user.
 */
import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error("❌ DATABASE_URL not set");
  process.exit(1);
}

const adapter = new PrismaPg({ connectionString });
const db = new PrismaClient({ adapter });

async function resetAndSeed() {
  try {
    console.log("🗑  Truncating test data...");

    // Delete in FK-safe order (children first)
    await db.$executeRawUnsafe(`
      TRUNCATE TABLE
        "CollectorReleaseSelection",
        "CollectorCreatorSubscription",
        "ReleaseArtwork",
        "ReleaseTag",
        "GeneratedPrintFile",
        "PricingQuoteSnapshot",
        "Release",
        "Artwork",
        "CreatorSocialLink",
        "CreatorPayoutProfile",
        "CreatorProfile",
        "CollectorProfile",
        "NotificationPreference",
        "EmailNotificationLog",
        "UserRole",
        "Session",
        "Account",
        "VerificationToken",
        "User",
        "SubscriptionCycle",
        "BookletConstraint"
      CASCADE
    `);

    console.log("✅ Database cleared");

    // ---- Creator test user ------------------------------------------------
    const creatorUserId = randomUUID();
    const creatorSessionToken = randomUUID();

    const creatorUser = await db.user.create({
      data: {
        id: creatorUserId,
        email: "creator@test.digiart",
        name: "Test Creator",
      },
    });

    await db.session.create({
      data: {
        sessionToken: creatorSessionToken,
        userId: creatorUser.id,
        expires: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      },
    });

    await db.userRole.create({
      data: { userId: creatorUser.id, role: "CREATOR" },
    });

    // ---- No-role user (for onboarding tests) ------------------------------
    const noRoleUserId = randomUUID();
    const noRoleSessionToken = randomUUID();

    const noRoleUser = await db.user.create({
      data: {
        id: noRoleUserId,
        email: "norole@test.digiart",
        name: "No Role User",
      },
    });

    await db.session.create({
      data: {
        sessionToken: noRoleSessionToken,
        userId: noRoleUser.id,
        expires: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      },
    });

    // ---- Booklet constraint -----------------------------------------------
    await db.bookletConstraint.create({
      data: {
        id: "test-constraint-1",
        minPages: 30,
        maxPages: 50,
        isActive: true,
        version: 1,
      },
    });

    // ---- Open subscription cycle ------------------------------------------
    const now = new Date();
    const month = now.getMonth() + 1;
    const year = now.getFullYear();

    await db.subscriptionCycle.create({
      data: {
        label: `${now.toLocaleString("default", { month: "long" })} ${year}`,
        month,
        year,
        selectionOpenDate: new Date(year, month - 1, 1),
        lockDate: new Date(year, month - 1, 28),
        fulfillmentDate: new Date(year, month, 1),
        status: "OPEN",
      },
    });

    // ---- Write credentials to .env.test.local ----------------------------
    const envContent = `# Auto-generated by reset-test-db.ts — DO NOT EDIT MANUALLY
AUTH_BYPASS_TEST_USER_ID="${creatorUser.id}"
TEST_SESSION_TOKEN="${creatorSessionToken}"
NO_ROLE_USER_ID="${noRoleUser.id}"
NO_ROLE_SESSION_TOKEN="${noRoleSessionToken}"
`;

    writeFileSync(resolve(__dirname, "../.env.test.local"), envContent);

    console.log("");
    console.log("🌱 Seed complete");
    console.log(`   Creator user:  ${creatorUser.email} (${creatorUser.id})`);
    console.log(`   No-role user:  ${noRoleUser.email} (${noRoleUser.id})`);
    console.log("   Cycle: OPEN");
    console.log("   BookletConstraint: 30-50 pages");
    console.log("");
    console.log("📝 Written to .env.test.local");
    console.log("🚀 Run: pnpm test:e2e");
  } catch (err) {
    console.error("❌ Reset failed:", err);
    process.exit(1);
  } finally {
    await db.$disconnect();
  }
}

resetAndSeed();
