#!/usr/bin/env node
/**
 * Resets the test database to a clean state, then seeds the minimum data
 * needed for E2E tests:
 *  - Creator test user (CREATOR role) + fresh session token
 *  - No-role user + fresh session token
 *  - BookletConstraint + open SubscriptionCycle
 *
 * User IDs are FIXED (hardcoded below) so AUTH_BYPASS_TEST_USER_ID can live
 * permanently in .env.test and the server never needs a restart after reset.
 * Only the session tokens are written to .env.test.local.
 */
import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error("❌ DATABASE_URL not set");
  process.exit(1);
}

const adapter = new PrismaPg({ connectionString });
const db = new PrismaClient({ adapter });

// Fixed UUIDs — these never change so AUTH_BYPASS_TEST_USER_ID can be
// hardcoded in .env.test and the running server needs no restart after reset.
const CREATOR_USER_ID = "00000000-e2e0-0000-0000-000000000001";
const NO_ROLE_USER_ID = "00000000-e2e0-0000-0000-000000000002";

async function resetAndSeed() {
  try {
    console.log("🗑  Truncating test data...");

    // Delete in FK-safe order (children first)
    await db.$executeRawUnsafe(`
      TRUNCATE TABLE
        "CollectorReleaseSelection",
        "CollectorCreatorSubscription",
        "ReleaseArtwork",
        "ReleaseTag",
        "GeneratedPrintFile",
        "PricingQuoteSnapshot",
        "Release",
        "Artwork",
        "CreatorSocialLink",
        "CreatorPayoutProfile",
        "CreatorProfile",
        "CollectorProfile",
        "NotificationPreference",
        "EmailNotificationLog",
        "UserRole",
        "Session",
        "Account",
        "VerificationToken",
        "User",
        "SubscriptionCycle",
        "BookletConstraint"
      CASCADE
    `);

    console.log("✅ Database cleared");

    // ---- Creator test user ------------------------------------------------
    const creatorSessionToken = randomUUID();

    const creatorUser = await db.user.create({
      data: {
        id: CREATOR_USER_ID,
        email: "creator@test.digiart",
        name: "Test Creator",
      },
    });

    await db.session.create({
      data: {
        sessionToken: creatorSessionToken,
        userId: creatorUser.id,
        expires: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      },
    });

    await db.userRole.create({
      data: { userId: creatorUser.id, role: "CREATOR" },
    });

    // ---- No-role user (for onboarding tests) ------------------------------
    const noRoleSessionToken = randomUUID();

    const noRoleUser = await db.user.create({
      data: {
        id: NO_ROLE_USER_ID,
        email: "norole@test.digiart",
        name: "No Role User",
      },
    });

    await db.session.create({
      data: {
        sessionToken: noRoleSessionToken,
        userId: noRoleUser.id,
        expires: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      },
    });

    // ---- Booklet constraint -----------------------------------------------
    await db.bookletConstraint.create({
      data: {
        id: "test-constraint-1",
        minPages: 30,
        maxPages: 50,
        isActive: true,
        version: 1,
      },
    });

    // ---- Open subscription cycle ------------------------------------------
    const now = new Date();
    const month = now.getMonth() + 1;
    const year = now.getFullYear();

    // lockDate is always 30 days out so the cycle is OPEN whenever tests run
    const lockDate = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    const fulfillmentDate = new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000);

    await db.subscriptionCycle.create({
      data: {
        label: `${now.toLocaleString("default", { month: "long" })} ${year}`,
        month,
        year,
        selectionOpenDate: new Date(year, month - 1, 1),
        lockDate,
        fulfillmentDate,
        status: "OPEN",
      },
    });

    // ---- Write session tokens to .env.test.local -------------------------
    // IDs are fixed so AUTH_BYPASS_TEST_USER_ID lives in .env.test permanently.
    // Only the rotating session tokens go here.
    const envContent = `# Auto-generated by reset-test-db.ts — DO NOT EDIT MANUALLY
TEST_SESSION_TOKEN="${creatorSessionToken}"
NO_ROLE_SESSION_TOKEN="${noRoleSessionToken}"
`;

    writeFileSync(resolve(__dirname, "../.env.test.local"), envContent);

    console.log("");
    console.log("🌱 Seed complete");
    console.log(`   Creator user:  ${creatorUser.email} (${creatorUser.id})`);
    console.log(`   No-role user:  ${noRoleUser.email} (${noRoleUser.id})`);
    console.log("   Cycle: OPEN");
    console.log("   BookletConstraint: 30-50 pages");
    console.log("");
    console.log("📝 Written to .env.test.local (session tokens only)");
    console.log(
      "💡 AUTH_BYPASS_TEST_USER_ID is fixed in .env.test — no server restart needed",
    );
    console.log("🚀 Run: pnpm test:e2e");
  } catch (err) {
    console.error("❌ Reset failed:", err);
    process.exit(1);
  } finally {
    await db.$disconnect();
  }
}

resetAndSeed();
